import {
  Home,
  Users,
  BookOpen,
  Activity,
  QrCode,
  ShoppingCart,
  History,
  UserCheck,
  BarChart3,
  AlertTriangle,
  Database,
  Monitor,
  Settings,
  UserPen,
  FolderTree,
  Building2,
  Package,
  User,
} from "lucide-react";
export const LibrarianNavBarData  = 
[
          {
            id: "dashboard",
            label: "Dashboard",
            icon: Home,
            link: "/admin/dashboard",
          },
          {
            id: "users",
            label: "User Management",
            icon: Users,
            link: "/admin/users",
          },
          {
            id: "books",
            label: "Book Management",
            icon: BookOpen,
            link: "/admin/books",
          },
          {
            id: "authors",
            label: "Author Management",
            icon: UserPen,
            link: "/admin/authors",
          },
          {
            id: "categories",
            label: "Category Management",
            icon: FolderTree,
            link: "/admin/categories",
          },
          {
            id: "publishers",
            label: "Publisher Management",
            icon: Building2,
            link: "/admin/publishers",
          },
          {
            id: "inventory",
            label: "Book Inventory",
            icon: Package,
            link: "/admin/inventory",
          },
          {
            id: "scanner",
            label: "QR Scanner",
            icon: QrCode,
            link: "/admin/scanner",
          },
          {
            id: "overdue",
            label: "Overdue Alerts",
            icon: AlertTriangle,
            link: "/admin/overdue",
          },
          {
            id: "history",
            label: "Borrowing History",
            icon: History,
            link: "/admin/history",
          },
          {
            id: "account",
            label: "Manage My Account",
            icon: User,
            link: "/admin/account",
          },
          {
            id: "features",
            label: "Features",
            icon: Settings,
            link: "/admin/feature",
          },
          {
            id: "book-catalog",
            label: "Book Catalog",
            icon: BookOpen,
            link: "/admin/bookcatalog",
          },
          {
            id: "cart",
            label: "My Cart",
            icon: ShoppingCart,
            link: "/admin/cart",
          },
        ]
